/**
 * WorkeaCheck™ — Question Bank
 * Each area has 5 questions. Each question has type, name, text, and options.
 * Types: 'scale' (1-5), 'radio', 'select'
 */

export const QUESTIONS = {
  fin: [
    {
      id: "fv",
      type: "scale",
      code: "F-1",
      text: "¿Qué tan clara es tu visibilidad sobre ingresos y gastos mes a mes?",
      min: "Sin visibilidad",
      max: "Visibilidad total",
      weight: 30,
    },
    {
      id: "fe",
      type: "radio",
      code: "F-2",
      text: "¿Conoces con precisión el punto de equilibrio de tu empresa?",
      weight: 20,
      options: [
        { value: "si", label: "Sí, lo calculo formalmente" },
        { value: "par", label: "Lo estimo, no formalmente" },
        { value: "no", label: "No lo sé" },
      ],
    },
    {
      id: "fc",
      type: "radio",
      code: "F-3",
      text: "¿Quién lleva la contabilidad de tu empresa?",
      weight: 20,
      options: [
        { value: "ext", label: "Contador externo certificado" },
        { value: "int", label: "Equipo interno especializado" },
        { value: "yo", label: "Yo mismo" },
        { value: "nada", label: "Nadie formalmente" },
      ],
    },
    {
      id: "fd",
      type: "scale",
      code: "F-4",
      text: "¿Qué tan preparado estás para tomar decisiones financieras basadas en datos?",
      min: "Nada preparado",
      max: "Totalmente preparado",
      weight: 15,
    },
    {
      id: "ff",
      type: "radio",
      code: "F-5",
      text: "¿Tu empresa tiene proyecciones financieras para los próximos 12 meses?",
      weight: 15,
      options: [
        { value: "si", label: "Sí, documentadas y actualizadas" },
        { value: "men", label: "Tengo proyecciones mentales" },
        { value: "no", label: "No tenemos proyecciones" },
      ],
    },
  ],

  mar: [
    {
      id: "mp",
      type: "scale",
      code: "M-1",
      text: "¿Qué tan consistente y profesional es la imagen visual de tu marca?",
      min: "Inconsistente",
      max: "Muy consistente",
      weight: 25,
    },
    {
      id: "mi",
      type: "radio",
      code: "M-2",
      text: "¿Tu empresa tiene presencia activa en redes sociales o plataformas digitales?",
      weight: 25,
      options: [
        { value: "si", label: "Sí, activa y estratégica" },
        { value: "par", label: "Parcialmente, sin estrategia clara" },
        { value: "no", label: "No tenemos presencia digital" },
      ],
    },
    {
      id: "mc",
      type: "radio",
      code: "M-3",
      text: "¿Tienes una propuesta de valor diferenciada y documentada?",
      weight: 20,
      options: [
        { value: "si", label: "Sí, documentada y comunicada al equipo" },
        { value: "men", label: "La tengo en mente, no documentada" },
        { value: "nada", label: "No hemos definido nuestra propuesta de valor" },
      ],
    },
    {
      id: "mq",
      type: "scale",
      code: "M-4",
      text: "¿Qué tan bien defines y segmentas a tu cliente ideal?",
      min: "No definido",
      max: "Muy bien definido",
      weight: 15,
    },
    {
      id: "ms",
      type: "radio",
      code: "M-5",
      text: "¿Mides el retorno de tus inversiones en marketing?",
      weight: 15,
      options: [
        { value: "si", label: "Sí, con métricas y KPIs definidos" },
        { value: "par", label: "Parcialmente, sin sistema formal" },
        { value: "no", label: "No medimos el retorno" },
      ],
    },
  ],

  ops: [
    {
      id: "oa",
      type: "radio",
      code: "O-1",
      text: "¿Tus procesos operativos están documentados y actualizados?",
      weight: 30,
      options: [
        { value: "si", label: "Sí, manuales y procedimientos vigentes" },
        { value: "par", label: "Parcialmente documentados" },
        { value: "no", label: "No están documentados" },
      ],
    },
    {
      id: "od",
      type: "scale",
      code: "O-2",
      text: "¿Qué tan bien puede funcionar tu negocio si tú no estás disponible por 2 semanas?",
      min: "Se detiene todo",
      max: "Funciona sin mí",
      weight: 30,
    },
    {
      id: "ot",
      type: "radio",
      code: "O-3",
      text: "¿Qué porcentaje de tus tareas operativas podrías delegar hoy?",
      weight: 20,
      options: [
        { value: "70", label: "Más del 70%" },
        { value: "40", label: "Entre 40% y 70%" },
        { value: "20", label: "Menos del 40%" },
        { value: "90", label: "Casi ninguna, soy el cuello de botella" },
      ],
    },
    {
      id: "ok",
      type: "scale",
      code: "O-4",
      text: "¿Qué tan estandarizadas son la calidad y la experiencia que entregas al cliente?",
      min: "Varía mucho",
      max: "Muy consistente",
      weight: 10,
    },
    {
      id: "om",
      type: "radio",
      code: "O-5",
      text: "¿Usas herramientas de gestión de proyectos o tareas en tu equipo?",
      weight: 10,
      options: [
        { value: "si", label: "Sí, toda la operación las usa" },
        { value: "par", label: "Solo parte del equipo" },
        { value: "no", label: "No usamos, todo es informal" },
      ],
    },
  ],

  tal: [
    {
      id: "ts",
      type: "scale",
      code: "T-1",
      text: "¿Qué tan satisfecho estás con el nivel de desempeño de tu equipo actual?",
      min: "Muy insatisfecho",
      max: "Muy satisfecho",
      weight: 25,
    },
    {
      id: "tp",
      type: "radio",
      code: "T-2",
      text: "¿Tienes un proceso formal de contratación documentado?",
      weight: 25,
      options: [
        { value: "si", label: "Sí, con criterios claros y etapas definidas" },
        { value: "inf", label: "Informal, depende del momento" },
        { value: "no", label: "No tenemos proceso de contratación" },
      ],
    },
    {
      id: "tf",
      type: "radio",
      code: "T-3",
      text: "¿Inviertes formalmente en formación o desarrollo de tu equipo?",
      weight: 20,
      options: [
        { value: "si", label: "Sí, presupuesto anual y plan definido" },
        { value: "oca", label: "Ocasionalmente, sin plan formal" },
        { value: "no", label: "No invertimos en formación" },
      ],
    },
    {
      id: "tm",
      type: "scale",
      code: "T-4",
      text: "¿Qué tan claro tiene cada persona su rol, responsabilidades y objetivos?",
      min: "Muy confuso",
      max: "Muy claro",
      weight: 20,
    },
    {
      id: "tr",
      type: "radio",
      code: "T-5",
      text: "¿Conoces la tasa de rotación de tu equipo y sus causas?",
      weight: 10,
      options: [
        { value: "si", label: "Sí, la mido y tengo estrategias de retención" },
        { value: "par", label: "La intuyo, sin datos formales" },
        { value: "no", label: "No la mido" },
      ],
    },
  ],

  leg: [
    {
      id: "lc",
      type: "radio",
      code: "L-1",
      text: "¿Tus contratos con clientes y proveedores están actualizados y son vinculantes?",
      weight: 30,
      options: [
        { value: "si", label: "Sí, revisados por asesor legal" },
        { value: "alg", label: "Algunos, pero no todos" },
        { value: "no", label: "No tengo contratos formales" },
      ],
    },
    {
      id: "lr",
      type: "radio",
      code: "L-2",
      text: "¿Tu empresa cumple con las regulaciones fiscales y laborales en Panamá?",
      weight: 25,
      options: [
        { value: "si", label: "Sí, estamos al día con todo" },
        { value: "par", label: "Parcialmente, con algunas brechas" },
        { value: "no", label: "No estoy seguro / tenemos pendientes" },
      ],
    },
    {
      id: "le",
      type: "radio",
      code: "L-3",
      text: "¿Cómo está constituida jurídicamente tu empresa?",
      weight: 20,
      options: [
        { value: "sa", label: "SA o SRL formalmente constituida" },
        { value: "ind", label: "Como persona natural independiente" },
        { value: "nat", label: "Aún no tiene estructura jurídica formal" },
        { value: "nse", label: "No sé exactamente" },
      ],
    },
    {
      id: "lp",
      type: "radio",
      code: "L-4",
      text: "¿Tu propiedad intelectual (marca, logo, software, contenido) está protegida legalmente?",
      weight: 15,
      options: [
        { value: "si", label: "Sí, registrada y protegida" },
        { value: "par", label: "Parcialmente protegida" },
        { value: "no", label: "No está protegida" },
      ],
    },
    {
      id: "lf",
      type: "scale",
      code: "L-5",
      text: "¿Qué tan preparado estás para enfrentar una disputa legal con un cliente o socio?",
      min: "Nada preparado",
      max: "Muy preparado",
      weight: 10,
    },
  ],

  tec: [
    {
      id: "kd",
      type: "scale",
      code: "K-1",
      text: "¿Qué tan digitalizada está la operación diaria de tu empresa?",
      min: "Todo manual",
      max: "Totalmente digital",
      weight: 30,
    },
    {
      id: "kc",
      type: "radio",
      code: "K-2",
      text: "¿Tienes un CRM o sistema para gestionar clientes y ventas?",
      weight: 25,
      options: [
        { value: "si", label: "Sí, con datos actualizados y en uso" },
        { value: "xls", label: "Usamos hojas de cálculo o Excel" },
        { value: "no", label: "No tenemos ningún sistema" },
      ],
    },
    {
      id: "ki",
      type: "radio",
      code: "K-3",
      text: "¿Tu empresa usa herramientas de IA o automatización en sus procesos?",
      weight: 20,
      options: [
        { value: "si", label: "Sí, de forma integrada" },
        { value: "exp", label: "Estamos explorando, sin implementar" },
        { value: "no", label: "No usamos IA ni automatización" },
      ],
    },
    {
      id: "ks",
      type: "radio",
      code: "K-4",
      text: "¿Tu empresa tiene políticas de seguridad de datos y ciberseguridad?",
      weight: 15,
      options: [
        { value: "si", label: "Sí, documentadas y aplicadas" },
        { value: "bas", label: "Solo medidas básicas informales" },
        { value: "no", label: "No tenemos políticas de seguridad" },
      ],
    },
    {
      id: "km",
      type: "scale",
      code: "K-5",
      text: "¿Qué tan bien integradas están tus herramientas tecnológicas entre sí?",
      min: "Desconectadas",
      max: "Totalmente integradas",
      weight: 10,
    },
  ],

  est: [
    {
      id: "ev",
      type: "radio",
      code: "E-1",
      text: "¿Tienes una visión documentada de dónde estará tu empresa en 3 años?",
      weight: 30,
      options: [
        { value: "si", label: "Sí, documentada y compartida con el equipo" },
        { value: "men", label: "La tengo en mente, no documentada" },
        { value: "no", label: "No tenemos visión definida" },
      ],
    },
    {
      id: "es",
      type: "radio",
      code: "E-2",
      text: "¿Tu modelo de negocio actual es escalable sin incrementar costos proporcionalmente?",
      weight: 25,
      options: [
        { value: "si", label: "Sí, está diseñado para escalar" },
        { value: "par", label: "Parcialmente, con limitaciones" },
        { value: "no", label: "No, los costos crecen linealmente con el ingreso" },
        { value: "nse", label: "No lo he analizado formalmente" },
      ],
    },
    {
      id: "em",
      type: "scale",
      code: "E-3",
      text: "¿Qué tan activa es tu red de mentores, alianzas o contactos estratégicos?",
      min: "Inexistente",
      max: "Muy activa",
      weight: 20,
    },
    {
      id: "ef",
      type: "radio",
      code: "E-4",
      text: "¿Has accedido o estás evaluando fuentes de financiamiento externo (inversión, crédito, grants)?",
      weight: 15,
      options: [
        { value: "si", label: "Sí, actualmente tenemos o exploramos opciones" },
        { value: "int", label: "Lo hemos pensado pero no actuado" },
        { value: "no", label: "No lo hemos considerado" },
      ],
    },
    {
      id: "ek",
      type: "scale",
      code: "E-5",
      text: "¿Qué tan alineado está tu equipo con los objetivos estratégicos de la empresa?",
      min: "Nada alineado",
      max: "Totalmente alineado",
      weight: 10,
    },
  ],
};
